### PR TITLE
feat: Add macros to create synchronous Python functions from async Rust functions.

### LINKED ISSUE #47: Feature: Add macros for exporting an asynchronous Rust functions as synchronous.
In qcs-sdk-rust, we have some macros that wrap an async Rust function, and export it as a synchronous and asynchronous function to Python. That is useful for more than just that project, so we should add it to this package.

### PR DESCRIPTION
**Pull request by MarquessV**
closes #47

### CODE REVIEW

**Comment by Shadow53** [comment]
There's a few broken intra-doc links that look like things we can fix. Can you fix those here so CI is green?

**Comment by MarquessV** [comment]
> There's a few broken intra-doc links that look like things we can fix. Can you fix those here so CI is green?

I've been trying to fix those, but I find them puzzling. The check says they are invalid URLs, but they work when I build them. `cargo make deadlinks` doesn't report any errors locally either.

**Comment by Shadow53** [comment]
> The check says there are invalid URLs, but they work when I build them. `cargo make deadlinks` doesn't report any errors locally either.

They are showing up for me. Maybe do a `cargo clean` first?

```
$ cargo -V; rustc -V; cargo make --version
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)
cargo-make 0.37.12
```

**Comment by MarquessV** [comment]
> 
> They are showing up for me. Maybe do a `cargo clean` first?
> 

A `cargo clean` actually worked. That said, I feel like the error is bogus. The links _do_ work in the documentation. I added an explicit target, which fixes the cargo-deadlinks error, but `rustdoc` raises a warning that the explicit target is redundant 🤷

**Review by Shadow53 — APPROVED** [review]

**Pull request merged**
